### ISSUE TITLE
May I contribute your package to conda-forge?

### ISSUE THREAD

**Issue by JunSeokCha** [neurophysik/jitcxde_common#3]
Dear neurophysik,

Hello neurophysik, my name is JunSeokCha and I am a student. I found that your package is on pypi but not on conda-forge. May I submit your package to conda-forge? Would you allow me to add jitcxde, jitcode, jitcdde, jitcsde to conda-forge?

If you would like me to do so, then who would you like to be the maintainer of the conda-forge feedstock for your package?

The job of the maintainer of the feedstock is to:
Keep the feedstock updated by merging eventual maintenance PRs from conda-forge’s bots.
Keep the feedstock on par with new releases of the source package by:
Bumping the version number and checksum.
Making sure that the feedstock’s requirements stay accurate.
Make sure the test requirements match those of the updated package.
Answer eventual questions about the package on the feedstock issue tracker.

If you would like to be the maintainer of the conda-forge feedstock, then I will submit your name as the maintainer of feedstock in the conda-forge recipe. If you would not like to be the maintainer of the conda-forge feedstock, then I will submit my name on the conda-forge recipe as maintainer of feedstock.

Sincerely,
JunSeokCha

**Comment by Wrzlprmft** [comment]
I have no objection if you do this and also maintain the package. As far as I can tell, the license should allow this anyway. I wouldn’t want to maintain the package, but if you have any questions, feel free to contact me.

Two thoughts:

* Note that JiTCDDE depend on [CHSPy](https://github.com/neurophysik/CHSPy), which you probably also want to package.
* One of the advantages of Conda would be that it might be possible to include a reasonable, OS-sensitive dependency on a C compiler and possibly the required Python development packages.

**Comment by JunSeokCha** [comment]
Thank you for your answer. I will try contribute  your package to conda-forge after I get permissions to contribute CHSPy to conda-forge, too.

**Comment by JunSeokCha** [comment]
I found that CHSPy is a package made by your organization may I contribute it to conda-forge also?

**Comment by Wrzlprmft** [comment]
> I found that CHSPy is a package made by your organization may I contribute it to conda-forge also?

Sure.
